services:
  postgres:
    image: postgres
    container_name: mtcg_postgres
    environment:
      POSTGRES_USER: mtcg_user
      POSTGRES_PASSWORD: mtcg_password
      POSTGRES_DB: mtcg_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mtcg_network

networks:
  mtcg_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
