services:
  postgres:
    image: postgres
    container_name: mtcg_postgres
    environment:
      POSTGRES_USER: mtcg_user
      POSTGRES_PASSWORD: mtcg_password
      POSTGRES_DB: mtcg_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
     image: dpage/pgadmin4
     container_name: pgadmin
     ports:
      - "5050:80"
     environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.admin
      PGADMIN_DEFAULT_PASSWORD: admin

volumes:
  postgres_data:
    driver: local
